osx_image: xcode8
language: objective-c

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

# Test using Fastlane
script:
  - ./fastlane/travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
